
name: "armnn_tflite_nobatch_zero_1_object"
backend: "armnn_tflite"
max_batch_size: 0

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
