name: "mobilenet_v3_large_100_224"
backend: "armnn_tflite"
max_batch_size: 3
input [
    {
    name: "serving_default_inputs:0"
    data_type: TYPE_FP32
    dims: [ 224, 224, 3 ]
    }    
]
output [
    {
    name: "StatefulPartitionedCall:0"
    data_type: TYPE_FP32
    dims: [ 1001 ]
    label_filename: "labels.txt"
    }
]
instance_group [
    {
    count: 1
    kind: KIND_CPU
    }
]
